// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-FVJ-bw0ortRwt3W9zYCQfzXgPObbyPo',
    appId: '1:590432642469:web:955b9dfb36bb5d133ef44c',
    messagingSenderId: '590432642469',
    projectId: 'palacehotel-f5df2',
    authDomain: 'palacehotel-f5df2.firebaseapp.com',
    storageBucket: 'palacehotel-f5df2.firebasestorage.app',
    measurementId: 'G-CY0JBNMGWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ckiHd3aC-qNSvOwjdLIqYfKl-_bMvkM',
    appId: '1:590432642469:android:98a6bd6caa4826243ef44c',
    messagingSenderId: '590432642469',
    projectId: 'palacehotel-f5df2',
    storageBucket: 'palacehotel-f5df2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQxWK3HSnZeCBsv3AyRDFr2BJtsdX9eU',
    appId: '1:590432642469:ios:b38ec588fb1274bc3ef44c',
    messagingSenderId: '590432642469',
    projectId: 'palacehotel-f5df2',
    storageBucket: 'palacehotel-f5df2.firebasestorage.app',
    iosBundleId: 'com.example.palaceHotelManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQxWK3HSnZeCBsv3AyRDFr2BJtsdX9eU',
    appId: '1:590432642469:ios:b38ec588fb1274bc3ef44c',
    messagingSenderId: '590432642469',
    projectId: 'palacehotel-f5df2',
    storageBucket: 'palacehotel-f5df2.firebasestorage.app',
    iosBundleId: 'com.example.palaceHotelManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-FVJ-bw0ortRwt3W9zYCQfzXgPObbyPo',
    appId: '1:590432642469:web:d74479eefd4c746b3ef44c',
    messagingSenderId: '590432642469',
    projectId: 'palacehotel-f5df2',
    authDomain: 'palacehotel-f5df2.firebaseapp.com',
    storageBucket: 'palacehotel-f5df2.firebasestorage.app',
    measurementId: 'G-FBCFWJS3WP',
  );
}
